pom.xml
src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java

Error running this sink connector.
```
java.lang.NoClassDefFoundError: org/apache/pulsar/common/naming/TopicName
at org.apache.pulsar.io.jcloud.partitioner.Partitioner.generatePartitionedPath(Partitioner.java:61) ~[pulsar-io-cloud-storage-2.8.0-rc-202105251229.nar-unpacked/:?]
at org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink.buildPartitionPath(BlobStoreAbstractSink.java:229) ~[pulsar-io-cloud-storage-2.8.0-rc-202105251229.nar-unpacked/:?]
at org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink.unsafeFlush(BlobStoreAbstractSink.java:196) ~[pulsar-io-cloud-storage-2.8.0-rc-202105251229.nar-unpacked/:?]
at org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink.flush(BlobStoreAbstractSink.java:167) ~[pulsar-io-cloud-storage-2.8.0-rc-202105251229.nar-unpacked/:?]
at …
```

Make pulsar-common required and improve error logs

---

README.md
pom.xml
src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/format/AvroFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/BytesFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/JsonFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/ParquetFormat.java
src/main/java/org/apache/pulsar/io/jcloud/util/AvroRecordUtil.java
src/main/java/org/apache/pulsar/io/jcloud/util/MetadataUtil.java
src/test/java/org/apache/pulsar/io/jcloud/format/AvroFormatTest.java
src/test/java/org/apache/pulsar/io/jcloud/format/BytesFormatTest.java
src/test/java/org/apache/pulsar/io/jcloud/format/FormatTestBase.java
src/test/java/org/apache/pulsar/io/jcloud/format/ParquetFormatTest.java

fixed #31.
need add document.
Added `withMetadata` option to save metadata.
The default value of `withMetadata` is false.
When `withMetadata=true`, the format is json, avro, parquet, and metadata will be saved to the root of each piece of data.
```json
{
"type": "record",
"name": "TestRecord",
"namespace": "org.apache.pulsar.io.jcloud.bo",
"fields": [
{
"name": "name",
"type": [
"null",
"string"
],
"default": null
},
{
"name": "number",
"type": "int"
},
{
"name": "subRecord",
"type": [
"null",
{
"type": "record",
"name": "TestSubRecord",
"namespace": "org.apache.pulsar.io.jcloud.bo.TestRecord",
"fields": [
{
"name": "name",
"type": [
"null",
"string"
],
"default": null
}
]
}
],
"default": null
}
]
}
```
Data: 
```json
{
"name": "key1",
"number": 1,
"subRecord": null
}
```
```json
{ …
```

Save message attributes to metadata.

---

pom.xml

java8 and guice 3.0 ([ref](https://github.com/google/guice/issues/757)) has incompatible issue, and apache jclouds 2.2.x is using guice 3.0 ([ref](https://github.com/apache/jclouds/blob/2.2.x/project/pom.xml#L227)), this will cause cloud storage connector cannot init with java8.

bump jclouds to 2.3.0

---

pom.xml

*Motivation*
Pulsar 2.8 image is using Java 11. So we need to add additional dependencies to make sure it can be run on Pulsar 2.8 images.

Add missing dependency for Java 11

---

pom.xml
src/test/java/org/apache/pulsar/io/jcloud/PulsarTestBase.java
src/test/java/org/apache/pulsar/io/jcloud/container/PulsarContainer.java
src/test/java/org/apache/pulsar/io/jcloud/format/AvroFormatTest.java
src/test/java/org/apache/pulsar/io/jcloud/format/BytesFormatTest.java
src/test/java/org/apache/pulsar/io/jcloud/format/ParquetFormatTest.java
src/test/java/org/apache/pulsar/io/jcloud/partitioner/PartitionerTest.java
src/test/java/org/apache/pulsar/io/jcloud/partitioner/SliceTopicPartitionPartitionerTest.java

tests are using `pulsar-functions-instance` and it will pollute the dep tree of pulsar io connector. 
this PR removes the dep and use mock to run tests.

remove `pulsar-functions-instance` dep from tests

---

src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/partitioner/PartitionerType.java
src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java
src/test/java/org/apache/pulsar/io/jcloud/partitioner/PartitionerTypeTest.java

Currently, cloud-storage connector supports `partition` and `time` partitioner, but the code uses `default` and `partition` to indicate `partition`, and makes the `partition` type not work as expected.
This PR fixes the issue, and makes `partition` as the default partitioner

align `partitionerType` options

---

src/main/java/org/apache/pulsar/io/jcloud/credential/GcsCredential.java

`RuntimeSpawner quit because of
java.lang.IllegalArgumentException: The service account key path and key content is empty for GCS driver` when with `gcsServiceAccountKeyFilePath` given.

fix gcs credential

---

README.md
docs/io-cloud-storage-sink.md
src/main/java/org/apache/pulsar/io/jcloud/partitioner/TimePartitioner.java
src/test/java/org/apache/pulsar/io/jcloud/partitioner/PartitionerTest.java

Currently the time partitioner only support formatted interval string like `1d` or `10h`, and not support more precise scales like minutes and seconds, or even milliseconds. This PR allows user to use `m` and `s`, also allows user use milliseconds string directly to time partitioner.

support more scales to time partitioner

---

README.md
docs/io-cloud-storage-sink.md
src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/format/AvroFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/JsonFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/ParquetFormat.java
src/main/java/org/apache/pulsar/io/jcloud/util/MetadataUtil.java
src/test/java/org/apache/pulsar/io/jcloud/MetadataUtilTest.java

- added `humanReadableMessageId` in config, default to `false`
- write Pulsar's messageId in `ledgerId:entryId:partitionIndex:batchIndex`
- add tests

support `humanReadableMessageId`

---

README.md
docs/io-cloud-storage-sink.md
src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java
src/main/java/org/apache/pulsar/io/jcloud/sink/CloudStorageGenericRecordSink.java
src/test/java/org/apache/pulsar/io/jcloud/ConnectorConfigTest.java

- use fixed size queue to prevent caching too many messages
- add `pendingQueueSize` to allow custom queue size
- by default the `pendingQueueSize` will be `batchSize * 10`

use fixed size queue to cache messages

---

src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/test/java/org/apache/pulsar/io/jcloud/ConnectorConfigTest.java

https://github.com/streamnative/pulsar-io-cloud-storage/pull/163 supports more scales of time partitioner, but havnt change the config validator and will prevent user using the latest feature. This PR fixes the validator and add some more unit tests.

fix `timePartitioner` duration validation

---

src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/test/java/org/apache/pulsar/io/jcloud/ConnectorConfigTest.java

when using `bytes` format, `bytesFormatTypeSeparator` needs to be set and the `checkArgument` is using false condition, which will cause the bytes format cannot be used as expected.

fix `bytesFormatTypeSeparator` checkArgument with false condition

---

README.md
docs/io-cloud-storage-sink.md

#221 add new provider `s3v2` uses native AWS S3 client, this PR added docs to address the changes.

add new provider to docs

---

README.md
docs/io-cloud-storage-sink.md
src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/format/AvroFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/JsonFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/ParquetFormat.java
src/main/java/org/apache/pulsar/io/jcloud/util/MetadataUtil.java
src/test/java/org/apache/pulsar/io/jcloud/MetadataUtilTest.java

fix https://github.com/streamnative/pulsar-io-cloud-storage/issues/256
add `useHumanReadableSchemaVersion`
support convert schema version to plain string format instead of hex-encoded string

add `useHumanReadableSchemaVersion` to support plain format of schemaVersion in message metadata

---

src/main/java/org/apache/pulsar/io/jcloud/util/MetadataUtil.java
src/test/java/org/apache/pulsar/io/jcloud/MetadataUtilTest.java

change the schema version into Long type, sample: `"__message_metadata__":{"schemaVersion":0,"messageId":"10:427:-1:0","properties":{}}`

fix schema version format

---

src/main/java/org/apache/pulsar/io/jcloud/format/AvroFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/ParquetFormat.java
src/main/java/org/apache/pulsar/io/jcloud/util/AvroRecordUtil.java

Fixes #268
cloud-storage connector uses AVRO utils to write avro or parquet messages, and it needs to convert the Pulsar schema to AVRO schema, this PR adds the support of PROTOBUF_NATIVE and can convert the schema correctlly with AVRO utils.
*(or)*
*(or)*
*(example:)*
- Dependencies (does it add or upgrade a dependency): (yes / no)
- …

fix cannot parse PROTOBUF_NATIVE schema

---

src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/test/java/org/apache/pulsar/io/jcloud/ConnectorConfigTest.java

Fixes #14 
This fixes a misleading Java heap space error during runtime because the provider SDK requires the URI scheme
Validates the URI scheme of the endpoint, and also cleans up some code.
- Added test that expects failure when using a malformed endpoint
- Dependencies (does it add or upgrade a dependency): (yes / *no*)
- The public API: (yes / *no*)
- The schema: (yes / *no* / don't know)
- The default values of configurations: (yes / *no*)
- The wire protocol: (yes / *no*)
- The rest endpoints: (yes / *no*)
- The admin cli options: (yes / *no*)
- Anything that affects deployment: (yes / *no* / don't know)
- Does this pull request introduce a new feature? (yes / *no*)
- If yes, …

[#14][config] Validate endpoint URI scheme

---

src/main/java/org/apache/pulsar/io/jcloud/format/Format.java
src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java

Fixes #458 
If the connector was reading from multiple topics, the records would end up getting mixed. This is because for each batch the sink would only look at the first record to determine which topic it came from.
Divide records of the batch by topic, then for each topic verify the schema and upload to the correct blob for the respective topic. 
Also had to make a small change to when the partitioning timestamp is created, so that all records in one batch will end up having the same timestamp, irrespective of their topic.
* Had to manually test this change
- Dependencies (does it add or upgrade a dependency): (yes / *no*)
- The public API: (yes / *no*)
- The schema: (yes / *no* / don't know)
- The default values of configurations: …

[#458][sink] Fix multiple topics in the same output blob

---

src/main/java/org/apache/pulsar/io/jcloud/format/AvroFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/JsonFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/ParquetFormat.java
src/main/java/org/apache/pulsar/io/jcloud/util/AvroRecordUtil.java
src/test/java/org/apache/pulsar/io/jcloud/PulsarTestBase.java
src/test/java/org/apache/pulsar/io/jcloud/format/AvroFormatTest.java
src/test/java/org/apache/pulsar/io/jcloud/format/BytesFormatTest.java
src/test/java/org/apache/pulsar/io/jcloud/format/FormatTestBase.java
src/test/java/org/apache/pulsar/io/jcloud/format/JsonFormatTest.java

KeyValue is not supported in any format.
* Added support for KeyValue schema for all the formats. The output struct has "key" and "value" fields.

Support for KeyValue schema

---

README.md
docs/io-cloud-storage-sink.md

Fixes #154 
Adds pathPrefix description to docs.
**no**
- Dependencies (does it add or upgrade a dependency): (yes / no)
- The public API: (yes / no)
- The schema: (yes / no / don't know)
- The default values of configurations: (yes / no)
- The wire protocol: (yes / no)
- The rest endpoints: (yes / no)
- The admin cli options: (yes / no)
- Anything that affects deployment: (yes / no / don't know)
- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (not applicable / **docs** / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this …

[#154][docs] Add pathPrefix to docs

---

src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java

Every time a new flush is scheduled (`batchTimeMs` 1sec by default) there's a log line that says the queue is empty.
* Moved that log line to debug level

Move log 'Skip flushing because the pending flush is empty' to debug level

---

README.md
docs/io-cloud-storage-sink.md
src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/format/ParquetFormat.java

In the parquet format the compression is always `gzip`. The compressor mechanism passes through the hadoop library that has a memory leak for the gzip codec, see https://issues.apache.org/jira/browse/HADOOP-12007
There's no fix available yet. The only way to avoid the leak it would be to use another algorithm. 
* Added new config option `parquetCodec` (similar to ´AvroCodec´) that accepts a String. The string must be a available compression algorithm. The default value is still `gzip` for compatibiliy.
* Added docs
- Does this pull request introduce a new feature? (yes)
- If yes, how is the feature documented? (docs)

Make compression algorithm configurable for parquet format

---

pom.xml
src/checkstyle/checkstyle.xml
src/main/java/org/apache/pulsar/io/jcloud/format/JsonFormat.java
src/main/java/org/apache/pulsar/io/jcloud/sink/CloudStorageGenericRecordSink.java
src/main/java/org/apache/pulsar/io/jcloud/writer/JCloudsBlobWriter.java
src/main/java/org/apache/pulsar/io/jcloud/writer/S3BlobWriter.java
src/test/java/org/apache/pulsar/io/jcloud/format/JsonFormatTest.java
src/test/java/org/apache/pulsar/io/jcloud/writer/S3BlobWriterTest.java

closes #11 
This PR bumps checkstyle to 8.29
upgrading checkstyle version to 8.29
upgrading maven-checkstyle-plugin version to 3.1.1
fix violations due to checkstyle breaking changes

Bump checkstyle to 8.29

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #472 
The current PR template is not compatible with the auto-labeling for the docs. It also contains a copy-pasted section that is only relevant to apache/pulsar and not this connector in particular.
Added the docs section for auto labeling
Removed the misleading section about components

[#472][misc] Update PULL_REQUEST_TEMPLATE.md for auto-labeling

---

src/main/java/org/apache/pulsar/io/jcloud/util/AvroRecordUtil.java

Fix an NPE caused by [PR315](https://github.com/streamnative/pulsar-io-cloud-storage/pull/315).
The PR315 adds the below code block. If there is a Bytes schema in the record, the `record.getValue().getSchemaVersion() ` will be null, and `getPulsarInternalSchema(record.getMessage().orElse(null))` will return the consumer schema which may be an AutoSchema.
```java
if (record.getValue().getSchemaVersion() == null) {
org.apache.pulsar.client.api.Schema<GenericRecord> internalSchema =
getPulsarInternalSchema(record.getMessage().orElse(null));
if (internalSchema != null) {
schema = recoverGenericProtobufNativeSchemaFromInternalSchema(internalSchema);
}
}
```
If the `internalSchema` is an AutoConusme Schema, `schema.getSchemaInfo()` will be null. And the `schema.getSchemaInfo().getType() `will …

Fix Bytes schema is conversed to AutoConsume schema

---

src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java

In case there is an Exception happening during the retrieval of the schema, the sink fails.
Exceptions happening during schema retrieval are caught, logged and records are failed/nacked.
*(or)*
*(or)*
*(example:)*

[fix][sink] Fix sink failing upon schema retrieval exceptions

---

src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java

Improve the uploaded logging it is per partition not the entire batch that is misleading in the log.
Correlate the uploaded blob to a topic and the size of uploaded blob is also per topic or per partition. It is not the entire batch to be uploaded to a single blob
it's a logging fix

Improve the uploaded logging 

---

src/main/java/org/apache/pulsar/io/jcloud/format/JsonFormat.java
src/test/java/org/apache/pulsar/io/jcloud/format/FormatTestBase.java
src/test/java/org/apache/pulsar/io/jcloud/format/JsonFormatTest.java

#623 
- When using `Map<String,Object>` convert failed, try to use `List<Map<String, Object>>` the second convert.
- Which way `Map<String, Object>` and `List<Map<String, Object>>` can be converted successfully, the next convert will try to use it first.
- Add `testJsonBytesRecordWriter` and `testJsonStringRecordWriter` to cover it.

Fix JsonFormat convert failed when use array jsonBytes or jsonString.

---

pom.xml
src/test/java/org/apache/pulsar/io/jcloud/format/FormatTestBase.java

Upgrade depends sn-pulsar version to 2.11.0.4 on the master branch to ensure the unit test use the latest pulsar version.
- Change the sn-pulsar version to 2.11.0.4
- Since https://github.com/apache/pulsar/pull/15622 change `Message#getReaderSchema()`  behavior, So, we need add judge on unit test.

Upgrade depends pulsar version to 2.11.0.4

---

src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/sink/CloudStorageSinkConfig.java
src/main/java/org/apache/pulsar/io/jcloud/writer/AzureBlobWriter.java
src/test/java/org/apache/pulsar/io/jcloud/ConnectorConfigTest.java

For Azure blob storage, when users set `azureStorageAccountConnectionString `, `endpoint` is not required.
- Change `endpoint` validation logic, only validate it when `azureStorageAccountConnectionString` is empty.
- Add `testAllowEndpointEmptyWithAzure ` and `testNotAllowEndpointEmptyWithAzure ` to cover it.

Optimize Azure blob storage connector config validation logic

---

src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java
src/test/java/org/apache/pulsar/io/jcloud/sink/CloudStorageGenericRecordSinkTest.java

In the existing logic, whether the flush operation fails or succeeds, the variables `currentBatchSize` and `currentBatchBytes` will be cleared. However, if an error such as an Out of Memory (OOM) exception occurs during the flush operation, it will be caught here: 
https://github.com/streamnative/pulsar-io-cloud-storage/blob/06d8c33afa7d813ffc2019ed4331a3883f9f9044/src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java#L217-L221
Nonetheless, the batch might not be cleared properly. This could result in an empty queue, despite `currentBatchSize` and `currentBatchBytes` not being reset to 0.
- The batch is now cleared before the actual flush operation takes place.
This change added tests。
(If you need help on updating docs, create …

fix: cleanup the current batch after flush crashed

---

proposals/Proposal-2-Support-Including-Topic-Name-To-Metadata.md

Currently, we don't include the topic name to the metadata. And there is not intuitive workaround for it.
This proposal introduces a new configuration `includeTopicName` to the Cloud Storage sink connector. When
activated(`true`), the connector will include the topic name to the metadata in the sink file.
Introduce a new configuration `includeTopicToMetadata` to support including the Pulsar topic name into the metadata.
The new data format of the cloud storage format would be like:
```json
{
"key": "value",
"__message_metadata__": {
"messageId": "CAgQADAA",
"topic": "persistent://public/default/test-s3",
"properties": {}
}
}
```
A new key, `topic`, would be added to the metadata, containing the Pulsar topic name.
(If you need help on updating …

[Proposal-2] Support including the topic name to the metadata

---

src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/format/AvroFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/JsonFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/ParquetFormat.java
src/main/java/org/apache/pulsar/io/jcloud/util/MetadataUtil.java
src/test/java/org/apache/pulsar/io/jcloud/MetadataUtilTest.java

Proposal link: https://github.com/streamnative/pulsar-io-cloud-storage/pull/860
Special release for https://github.com/streamnative/pulsar-io-cloud-storage/issues/816
See https://github.com/streamnative/pulsar-io-cloud-storage/issues/816
- Add new configuration `includeTopicToMetadata`
(cherry picked from commit 94620e41f2e0d1b03bf98c5914359016153b11b9)
Currently, we don't include the topic name to the metadata. And there is not intuitive workaround for it.
This proposal introduces a new configuration `includeTopicName` to the Cloud Storage sink connector. When
activated(`true`), the connector will include the topic name to the metadata in the sink file.
Introduce a new configuration `includeTopicToMetadata` to support including the Pulsar topic name into the metadata.
The new data format …

[feat][Proposal-2] Support including the topic name to the metadata(#836)

---

src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java

In https://github.com/streamnative/pulsar-io-cloud-storage/pull/845, we have deprecated `partitionerType` and recommand users to use `partitioner`.
Set the default value of `partitionerType` to `partition`. So that we could be able to not configure it. Otherwise, it will raise exceptions if we don't configure it.
- Add default value for the partitionType to `partition`

Add default value for the partitionType to `partition`

---

src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java

Currently, when the traffic is high, we can see that there might be several small batches flushed into S3 together with regular large batches.
The root cause is that there is a race condition problem occurs when sending messages to S3, especially during high throughput.
The problem arises when the flush process starts, but the task is still in the queue of the flushExecutor, and the `isFlushRunning` flag hasn't been updated to true promptly. During this interval (before `isFlushRunning` is updated in the flushExecutor), **each message sent to the connector initiates a new flush task to the flushExecutor**. Check the code here: https://github.com/streamnative/pulsar-io-cloud-storage/blob/e5b1113a3c5e073e82fa02b891c69be85b930346/src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstrac …

[fix] Fix small batches flushed into S3 together with normal large batches

---

src/test/java/org/apache/pulsar/io/jcloud/PulsarTestBase.java
src/test/java/org/apache/pulsar/io/jcloud/container/PulsarContainer.java

Fix ci: https://github.com/streamnative/pulsar-io-cloud-storage/actions/runs/8533562615/job/23376542105?pr=935
- Use the Apache images to run tests, in order to avoid permission issues.
Ci passed

Use the Apache images to run tests, in order to avoid permission issues.

---

.github/workflows/pr-test.yml
pom.xml
src/main/java/org/apache/pulsar/io/jcloud/format/BytesFormat.java
src/main/java/org/apache/pulsar/io/jcloud/util/AvroRecordUtil.java
src/test/java/org/apache/pulsar/io/jcloud/PulsarTestBase.java
src/test/java/org/apache/pulsar/io/jcloud/format/FormatTestBase.java

To fix the Parquet/Avro format with separated key value avro-avro messages
Updated lombook version.
Parquet/Avro format with separated key value avro-avro messages.

[fix]: fix Parquet/Avro format with separated key value avro-avro messages

---

docs/aws-s3-sink.md
docs/azure-blob-storage-sink.md
docs/google-cloud-storage-sink.md
src/main/java/org/apache/pulsar/io/jcloud/partitioner/AbstractPartitioner.java
src/main/java/org/apache/pulsar/io/jcloud/partitioner/SimplePartitioner.java
src/main/java/org/apache/pulsar/io/jcloud/partitioner/TimePartitioner.java
src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java
src/main/java/org/apache/pulsar/io/jcloud/writer/AzureBlobWriter.java
src/test/java/org/apache/pulsar/io/jcloud/partitioner/AbstractPartitionerTest.java
src/test/java/org/apache/pulsar/io/jcloud/partitioner/PartitionerTest.java
src/test/java/org/apache/pulsar/io/jcloud/partitioner/SliceTopicPartitionPartitionerTest.java
src/test/java/org/apache/pulsar/io/jcloud/sink/CloudStorageSinkBatchBlendTest.java
src/test/java/org/apache/pulsar/io/jcloud/sink/CloudStorageSinkBatchPartitionedTest.java

For azure blob storage, When sink some batch message, somtime will get an error for azure blob storage:
```
2024-11-04T01:43:57,072+0000 [pulsar-io-cloud-storage-sink-flush-0] ERROR org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink - Encountered unknown error writing to blob abhijith/testing-eh-kaka-sync/unbuffered-telemetryfeed-partition-28/2024-10-30/799132352513.json
com.azure.storage.blob.models.BlobStorageException: Status code 409, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:4506238d-001e-00df-085b-2eae40000000
Time:2024-11-04T01:43:57.0681430Z</Message></Error>"
at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
at …
```

Use messageId instead of sequence as file name by default

---

pom.xml

- https://github.com/streamnative/eng-support-tickets/issues/1987
- https://github.com/streamnative/eng-support-tickets/issues/1988
- Upgrade netty to fix CVE-2024-47535

Upgrade netty to fix CVE-2024-47535
