streamnative/pulsar-io-cloud-storage

src/main/java/org/apache/pulsar/io/jcloud/credential/AwsCredential.java
src/main/java/org/apache/pulsar/io/jcloud/sink/CloudStorageGenericRecordSink.java

Can not use spi under narClassloader, use resource loading method instead

fix resource load and s3 credential name

---

pom.xml
src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/format/BytesFormat.java
src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java
src/test/java/org/apache/pulsar/io/jcloud/format/BytesFormatTest.java
src/test/java/org/apache/pulsar/io/jcloud/format/FormatTestBase.java

Add raw message support

---

pom.xml

* Fixed cloud storage version to 2.8.0-rc-202105251229

Fixed cloud storage version to latest

---

README.md
conf/cloud-storage-sink-config.yaml
src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/partitioner/AbstractPartitioner.java
src/main/java/org/apache/pulsar/io/jcloud/partitioner/Partitioner.java
src/main/java/org/apache/pulsar/io/jcloud/partitioner/SimplePartitioner.java
src/main/java/org/apache/pulsar/io/jcloud/partitioner/TimePartitioner.java
src/test/java/org/apache/pulsar/io/jcloud/partitioner/SliceTopicPartitionPartitionerTest.java

fixed #29 
if set `sliceTopicPartitionPath=true`, the topic `public/default/test-partition-0` save path to `public/default/test/0/****`.
if use `sliceTopicPartitionPath` is default value `false`, save path to `public/default/test/test-partition-0/****`

Save path supports split topic and partition.

---

.github/workflows/release.yml
image/Dockerfile

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

add release image

---

.github/workflows/release.yml

fix release github action been triggered multiple times with new release

fix release been triggered multiple times

---

src/main/java/org/apache/pulsar/io/jcloud/util/MetadataUtil.java
src/test/java/org/apache/pulsar/io/jcloud/format/FormatTestBase.java

use `message`'s properties but not `schemaInfo`'s properties.

fix message properties not exposed properly

---

.github/workflows/release.yml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

fix release script

---

.github/workflows/release.yml
image/Dockerfile

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

use non-root runner

---

src/main/java/org/apache/pulsar/io/jcloud/sink/CloudStorageGenericRecordSink.java
src/main/java/org/apache/pulsar/io/jcloud/sink/CloudStorageSinkConfig.java
src/test/java/org/apache/pulsar/io/jcloud/ConnectorConfigTest.java

Use `IOConfigUtils.loadWithSecrets` to load configs from secret if exists.

support load config from secret

---

src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java

fix batch can have records more than the `batchSize`

fix `batchSize` limit

---

README.md
docs/io-cloud-storage-sink.md
src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/format/BytesFormat.java
src/main/java/org/apache/pulsar/io/jcloud/util/HexStringUtils.java
src/test/java/org/apache/pulsar/io/jcloud/ConnectorConfigTest.java
src/test/java/org/apache/pulsar/io/jcloud/HexStringUtilsTest.java
src/test/java/org/apache/pulsar/io/jcloud/format/BytesFormatTest.java
src/test/java/org/apache/pulsar/io/jcloud/format/FormatTestBase.java

https://github.com/streamnative/pulsar-io-cloud-storage/issues/147

add separator for raw format config

---

src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java

*Motivation*
When an uncaught exception is thrown during flushing data to cloud storage, it will cause the cloud storage sink stuck at flushing. Because the flushing flag is set to `true` and never set back to `false`.
This change moves all the flushing logic into a function called `unsafeFlush` and add a finally block to ensure flushing flag being set back to `false` even there is an exception thrown in between.
This PR also add more logs for troubleshooting purpose.

Add more error logs

---

src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

remove full records log

---

pom.xml

Upgrade Hadoop from 3.3.1 to 3.3.3
Fix #356

Upgrade Hadoop to 3.3.3

---

src/main/java/org/apache/pulsar/io/jcloud/util/AvroRecordUtil.java

Fixes https://github.com/streamnative/pulsar-io-cloud-storage/issues/367
*(or)*
*(or)*
*(example:)*
*If `yes` …

support extract schema without schema version for avro and json schema

---

src/main/java/org/apache/pulsar/io/jcloud/util/MetadataUtil.java

Fixes https://github.com/streamnative/pulsar-io-cloud-storage/issues/432
*(or)*
*(or)*
*(example:)*
- Dependencies (does it add or upgrade a dependency): (yes / no)
- The public API: (yes / …

make metadata schema version nullable

---

.github/workflows/release.yml
image/Dockerfile

This fixes the docker images which are not been released to Docker Hub in the past few weeks.
- Do not pull the runner image from the `streamNative` repo.
- Replace the `streamnative` repo with `docker.cloudsmith.io` in the image/Dockerfile.
*(or)*
*(or)*
*(example:)*
(If …

[fix][ci]Change the release process

---

.github/CODEOWNERS

Adds the ecosystem team as CODEOWNERS

[misc] Add @streamnative/ecosystem to CODEOWNERS

---

README.md

There is no section in the README that helps with troubleshooting certain issues.
Added troubleshooting section, adding first example of configuration issues.

[docs] Add troubleshooting section to readme

---

src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java

If there are failing records we currently never reset the `currentBatchSize` and `currentBatchBytes` respectively, causing them to only ever increase with time.
Reset the `currentBatchBytes` and `currentBatchSize` in `bulkHandleFailedRecords`
*(or)*
*(or)*
*(example:)* …

[fix][sink] Reset currentBatchSize & currentBatchBytes on failing records

---

.github/workflows/pr-test.yml
.github/workflows/release.yml
pom.xml

Master Issue: #592 
To stay consistent with the main Pulsar repo, we want to upgrade to JDK 17.
Modified pom + CI

[chore] Upgrade to JDK 17

---

pom.xml

Upgrade jackson version.

---

pom.xml

Upgrade snaky version

---

README.md
docs/aws-s3-sink.md

Refine permissions required for AWS S3.
Refine permissions required for AWS S3.
- Tested on local host.

Update permission describe for AWS S3.

---

docs/aws-s3-sink.md
docs/azure-blob-storage-sink.md
docs/google-cloud-storage-sink.md

Refactor create a connector section docs.
- Refactor create a connector section docs.
- Refine permission describe for aws-s3 connector.
- None

Refactor create a connector section docs.

---

docs/aws-s3-sink.md
docs/azure-blob-storage-sink.md

Fix typos in doc
Fix typos in doc
- None

Fix typos in doc

---

docs/aws-s3-sink.md
docs/azure-blob-storage-sink.md
docs/google-cloud-storage-sink.md

Fix format errors for note.

---

src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
src/main/java/org/apache/pulsar/io/jcloud/format/AvroFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/JsonFormat.java
src/main/java/org/apache/pulsar/io/jcloud/format/ParquetFormat.java
src/main/java/org/apache/pulsar/io/jcloud/util/MetadataUtil.java
src/test/java/org/apache/pulsar/io/jcloud/MetadataUtilTest.java

Special release for https://github.com/streamnative/pulsar-io-cloud-storage/issues/816
See https://github.com/streamnative/pulsar-io-cloud-storage/issues/816
- Add new configuration `includeTopicToMetadata`
This change is already covered by existing tests
Configure the connector with the following configurations:
```yaml
configs:
withMetadata: true
includeTopicToMetadata: true
```
The result would be:
```
{"key":"value","__message_metadata__":{"messageId":"CAgQADAA","topic":"persistent://public/default/test-s3","properties":{}}}
```

[feat] Support including the topic name to the metadata

---

.github/workflows/release.yml

https://github.com/nick-fields/retry?tab=readme-ov-file#ownership
Change nick-invision to nick-fields
- CI passed
Need to update docs? 

Update nick-invision to nick-fields

---

docs/aws-s3-sink.md

Add doc for https://github.com/streamnative/pulsar-io-cloud-storage/pull/845
After this PR gets approved, I will update the doc for other cloud storage connectors

Add AWS-S3-Sink doc for proposal-1

---

image/Dockerfile

Update base image

---

src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java

Fix typo in log in BlobStoreAbstractSink

---

pom.xml

Upgrade pulsar version to 3.2.2.1
Upgrade pulsar version to 3.2.2.1
- CI passed

Upgrade pulsar version to 3.2.2.1

---

pom.xml

cve: upgrade depend version

---

pom.xml

(cherry picked from commit b10d0f247745024b549c083f26e83928d767aa8a)

cve: upgrade depend version (#944)

---

pom.xml

https://github.com/streamnative/eng-support-tickets/issues/1668
https://github.com/streamnative/eng-support-tickets/issues/1673
*(or)*
*(or)*
*(example:)*

Fix prootbuf CVE-2024-7254

---

pom.xml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

[fix][sec] Upgrade Avro to 1.11.4 to address CVE-2024-47561

---

src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java

- Exist connector process when encounter exception

Exist connector process when encounter exception

---

src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java
src/test/java/org/apache/pulsar/io/jcloud/sink/CloudStorageSinkBatchBlendTest.java

First, send msg with the schema: 
```
private int id;
private String name;
```
And then send msg with the schema
```
private int id;
private String name;
private String lastname;
```
Will get error
```
java.lang.NullPointerException: Cannot invoke "org.apache.avro.Schema$Field.schema()" because "lastname" is null
at org.apache.pulsar.io.jcloud.util.AvroRecordUtil.convertGenericRecord(AvroRecordUtil.java:278) ~[?:?]
at org.apache.pulsar.io.jcloud.format.ParquetFormat.recordWriterBuf(ParquetFormat.java:269) ~[?:?]
at org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink.bindValue(BlobStoreAbstractSink.java:368) ~[?:?]
at org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink.unsafeFlush(BlobStoreAbstractSink.java:319) ~[?:?]
at org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink.flush(Bl …
```

Support schema evolution

---

.github/workflows/pr-test.yml
.github/workflows/release.yml
pom.xml

Support self release
Support self release

Support self release

---

pom.xml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

bump pulsar to 4.0.4.2
